// ════════════════════════════════════════════════════════════
//  PowderTrack — Resort & Forecast Data
//  In production this would come from a weather API
//  (Open-Meteo, Tomorrow.io, or a specialized ski API)
// ════════════════════════════════════════════════════════════

const RESORTS = [
  {
    id: 1,
    name: "Mammoth Mountain",
    region: "sierra",
    country: "USA",
    state: "CA",
    elevation: { base: 7953, summit: 11053 },
    base_in: 140,
    new48h_in: 14,
    forecast7d_in: 22,
    open_trails: 137,
    total_trails: 175,
    lifts_open: 22,
    lifts_total: 25,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 12,
    temp_f: 24,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { day: "Fri", snow: 4,  high: 28, low: 14 },
      { day: "Sat", snow: 8,  high: 22, low: 10 },
      { day: "Sun", snow: 6,  high: 25, low: 12 },
      { day: "Mon", snow: 2,  high: 30, low: 18 },
      { day: "Tue", snow: 1,  high: 32, low: 20 },
      { day: "Wed", snow: 0,  high: 35, low: 22 },
      { day: "Thu", snow: 1,  high: 33, low: 21 },
    ],
    season_total_in: 382,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-20 06:00",
    lat: 37.631, lon: -119.032,
  },
  {
    id: 2,
    name: "Park City Mountain",
    region: "wasatch",
    country: "USA",
    state: "UT",
    elevation: { base: 6900, summit: 10026 },
    base_in: 112,
    new48h_in: 10,
    forecast7d_in: 18,
    open_trails: 210,
    total_trails: 330,
    lifts_open: 34,
    lifts_total: 41,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 8,
    temp_f: 18,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 17, intermediate: 52, advanced: 31 },
    forecast: [
      { day: "Fri", snow: 5,  high: 22, low: 8  },
      { day: "Sat", snow: 7,  high: 20, low: 6  },
      { day: "Sun", snow: 4,  high: 24, low: 10 },
      { day: "Mon", snow: 2,  high: 28, low: 14 },
      { day: "Tue", snow: 0,  high: 30, low: 16 },
      { day: "Wed", snow: 3,  high: 26, low: 12 },
      { day: "Thu", snow: 5,  high: 23, low: 9  },
    ],
    season_total_in: 298,
    avalanche_danger: "High",
    last_updated: "2026-02-20 06:30",
    lat: 40.651, lon: -111.508,
  },
  {
    id: 3,
    name: "Vail",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 8120, summit: 11570 },
    base_in: 86,
    new48h_in: 6,
    forecast7d_in: 14,
    open_trails: 185,
    total_trails: 195,
    lifts_open: 30,
    lifts_total: 31,
    rating: 4.7,
    surface: "Groomed",
    wind_mph: 15,
    temp_f: 20,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 18, intermediate: 29, advanced: 53 },
    forecast: [
      { day: "Fri", snow: 2,  high: 24, low: 10 },
      { day: "Sat", snow: 4,  high: 21, low: 8  },
      { day: "Sun", snow: 5,  high: 22, low: 9  },
      { day: "Mon", snow: 2,  high: 27, low: 14 },
      { day: "Tue", snow: 1,  high: 30, low: 17 },
      { day: "Wed", snow: 0,  high: 33, low: 19 },
      { day: "Thu", snow: 2,  high: 28, low: 15 },
    ],
    season_total_in: 220,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-20 07:00",
    lat: 39.608, lon: -106.355,
  },
  {
    id: 4,
    name: "Whistler Blackcomb",
    region: "cascades",
    country: "Canada",
    state: "BC",
    elevation: { base: 2182, summit: 7494 },
    base_in: 192,
    new48h_in: 8,
    forecast7d_in: 36,
    open_trails: 190,
    total_trails: 200,
    lifts_open: 36,
    lifts_total: 37,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 20,
    temp_f: 19,
    visibility: "Fair",
    groomed_today: false,
    status: "open",
    terrain: { beginner: 20, intermediate: 55, advanced: 25 },
    forecast: [
      { day: "Fri", snow: 10, high: 22, low: 12 },
      { day: "Sat", snow: 12, high: 20, low: 10 },
      { day: "Sun", snow: 8,  high: 23, low: 13 },
      { day: "Mon", snow: 4,  high: 26, low: 16 },
      { day: "Tue", snow: 2,  high: 28, low: 18 },
      { day: "Wed", snow: 6,  high: 24, low: 14 },
      { day: "Thu", snow: 8,  high: 21, low: 11 },
    ],
    season_total_in: 450,
    avalanche_danger: "High",
    last_updated: "2026-02-20 05:00",
    lat: 50.116, lon: -122.948,
  },
  {
    id: 5,
    name: "Telluride",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 8725, summit: 13150 },
    base_in: 95,
    new48h_in: 4,
    forecast7d_in: 10,
    open_trails: 143,
    total_trails: 148,
    lifts_open: 18,
    lifts_total: 19,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 18,
    temp_f: 16,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 23, intermediate: 36, advanced: 41 },
    forecast: [
      { day: "Fri", snow: 1,  high: 20, low: 5  },
      { day: "Sat", snow: 3,  high: 18, low: 3  },
      { day: "Sun", snow: 4,  high: 19, low: 4  },
      { day: "Mon", snow: 1,  high: 24, low: 10 },
      { day: "Tue", snow: 0,  high: 28, low: 14 },
      { day: "Wed", snow: 1,  high: 26, low: 12 },
      { day: "Thu", snow: 2,  high: 23, low: 8  },
    ],
    season_total_in: 198,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-20 07:15",
    lat: 37.937, lon: -107.852,
  },
  {
    id: 6,
    name: "Chamonix Mont-Blanc",
    region: "alps",
    country: "France",
    state: "",
    elevation: { base: 3412, summit: 12605 },
    base_in: 98,
    new48h_in: 5,
    forecast7d_in: 16,
    open_trails: 40,
    total_trails: 44,
    lifts_open: 26,
    lifts_total: 28,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 22,
    temp_f: 14,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 12, intermediate: 38, advanced: 50 },
    forecast: [
      { day: "Fri", snow: 3,  high: 16, low: 2  },
      { day: "Sat", snow: 6,  high: 14, low: 0  },
      { day: "Sun", snow: 4,  high: 16, low: 2  },
      { day: "Mon", snow: 2,  high: 19, low: 5  },
      { day: "Tue", snow: 1,  high: 21, low: 7  },
      { day: "Wed", snow: 0,  high: 22, low: 8  },
      { day: "Thu", snow: 3,  high: 18, low: 4  },
    ],
    season_total_in: 210,
    avalanche_danger: "High",
    last_updated: "2026-02-20 08:00",
    lat: 45.923, lon: 6.869,
  },
  {
    id: 7,
    name: "Niseko United",
    region: "japan",
    country: "Japan",
    state: "Hokkaido",
    elevation: { base: 820, summit: 4278 },
    base_in: 155,
    new48h_in: 12,
    forecast7d_in: 28,
    open_trails: 60,
    total_trails: 60,
    lifts_open: 30,
    lifts_total: 30,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 6,
    temp_f: 21,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 30, intermediate: 40, advanced: 30 },
    forecast: [
      { day: "Fri", snow: 8,  high: 24, low: 14 },
      { day: "Sat", snow: 6,  high: 22, low: 12 },
      { day: "Sun", snow: 10, high: 20, low: 10 },
      { day: "Mon", snow: 4,  high: 25, low: 15 },
      { day: "Tue", snow: 2,  high: 27, low: 17 },
      { day: "Wed", snow: 6,  high: 23, low: 13 },
      { day: "Thu", snow: 8,  high: 21, low: 11 },
    ],
    season_total_in: 610,
    avalanche_danger: "Low",
    last_updated: "2026-02-20 04:00",
    lat: 42.797, lon: 140.688,
  },
  {
    id: 8,
    name: "Snowbird",
    region: "wasatch",
    country: "USA",
    state: "UT",
    elevation: { base: 7760, summit: 11000 },
    base_in: 130,
    new48h_in: 9,
    forecast7d_in: 20,
    open_trails: 127,
    total_trails: 139,
    lifts_open: 12,
    lifts_total: 13,
    rating: 4.7,
    surface: "Powder",
    wind_mph: 10,
    temp_f: 22,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 27, intermediate: 38, advanced: 35 },
    forecast: [
      { day: "Fri", snow: 4,  high: 25, low: 12 },
      { day: "Sat", snow: 8,  high: 21, low: 8  },
      { day: "Sun", snow: 5,  high: 23, low: 10 },
      { day: "Mon", snow: 2,  high: 27, low: 14 },
      { day: "Tue", snow: 1,  high: 30, low: 17 },
      { day: "Wed", snow: 0,  high: 32, low: 19 },
      { day: "Thu", snow: 3,  high: 27, low: 13 },
    ],
    season_total_in: 340,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-20 06:45",
    lat: 40.583, lon: -111.656,
  },
  {
    id: 9,
    name: "Mt. Baker",
    region: "cascades",
    country: "USA",
    state: "WA",
    elevation: { base: 3500, summit: 5089 },
    base_in: 210,
    new48h_in: 14,
    forecast7d_in: 32,
    open_trails: 38,
    total_trails: 38,
    lifts_open: 10,
    lifts_total: 10,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 25,
    temp_f: 28,
    visibility: "Fair",
    groomed_today: false,
    status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { day: "Fri", snow: 12, high: 30, low: 22 },
      { day: "Sat", snow: 10, high: 28, low: 20 },
      { day: "Sun", snow: 6,  high: 30, low: 22 },
      { day: "Mon", snow: 4,  high: 32, low: 24 },
      { day: "Tue", snow: 0,  high: 36, low: 26 },
      { day: "Wed", snow: 2,  high: 34, low: 24 },
      { day: "Thu", snow: 6,  high: 30, low: 22 },
    ],
    season_total_in: 520,
    avalanche_danger: "High",
    last_updated: "2026-02-20 06:00",
    lat: 48.858, lon: -121.679,
  },
  {
    id: 10,
    name: "Jackson Hole",
    region: "rockies",
    country: "USA",
    state: "WY",
    elevation: { base: 6311, summit: 10450 },
    base_in: 78,
    new48h_in: 3,
    forecast7d_in: 12,
    open_trails: 116,
    total_trails: 133,
    lifts_open: 13,
    lifts_total: 13,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 14,
    temp_f: 14,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 10, intermediate: 40, advanced: 50 },
    forecast: [
      { day: "Fri", snow: 1,  high: 18, low: 2  },
      { day: "Sat", snow: 4,  high: 16, low: 0  },
      { day: "Sun", snow: 4,  high: 17, low: 1  },
      { day: "Mon", snow: 2,  high: 22, low: 8  },
      { day: "Tue", snow: 1,  high: 26, low: 12 },
      { day: "Wed", snow: 0,  high: 28, low: 14 },
      { day: "Thu", snow: 2,  high: 24, low: 10 },
    ],
    season_total_in: 182,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-20 07:00",
    lat: 43.588, lon: -110.828,
  },
  {
    id: 11,
    name: "Squaw Valley (Palisades)",
    region: "sierra",
    country: "USA",
    state: "CA",
    elevation: { base: 6200, summit: 9050 },
    base_in: 118,
    new48h_in: 11,
    forecast7d_in: 18,
    open_trails: 170,
    total_trails: 178,
    lifts_open: 29,
    lifts_total: 30,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 16,
    temp_f: 26,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 25, intermediate: 45, advanced: 30 },
    forecast: [
      { day: "Fri", snow: 3,  high: 28, low: 16 },
      { day: "Sat", snow: 7,  high: 24, low: 12 },
      { day: "Sun", snow: 5,  high: 26, low: 14 },
      { day: "Mon", snow: 2,  high: 30, low: 18 },
      { day: "Tue", snow: 1,  high: 33, low: 21 },
      { day: "Wed", snow: 0,  high: 36, low: 23 },
      { day: "Thu", snow: 2,  high: 31, low: 19 },
    ],
    season_total_in: 310,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-20 06:00",
    lat: 39.196, lon: -120.236,
  },
  {
    id: 12,
    name: "Zermatt",
    region: "alps",
    country: "Switzerland",
    state: "",
    elevation: { base: 5315, summit: 12533 },
    base_in: 72,
    new48h_in: 4,
    forecast7d_in: 10,
    open_trails: 52,
    total_trails: 52,
    lifts_open: 52,
    lifts_total: 52,
    rating: 4.9,
    surface: "Packed Powder",
    wind_mph: 12,
    temp_f: 10,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 22, intermediate: 38, advanced: 40 },
    forecast: [
      { day: "Fri", snow: 2,  high: 14, low: -4 },
      { day: "Sat", snow: 4,  high: 12, low: -6 },
      { day: "Sun", snow: 2,  high: 13, low: -5 },
      { day: "Mon", snow: 1,  high: 16, low: -2 },
      { day: "Tue", snow: 0,  high: 18, low: 0  },
      { day: "Wed", snow: 1,  high: 16, low: -2 },
      { day: "Thu", snow: 3,  high: 14, low: -4 },
    ],
    season_total_in: 180,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-20 08:00",
    lat: 46.016, lon: 7.749,
  },
];

// Season snowfall comparison data (top resorts)
const SEASON_DATA = {
  labels: ["Niseko", "Mt. Baker", "Whistler", "Mammoth", "Snowbird", "Squaw"],
  current: [610, 520, 450, 382, 340, 310],
  avg: [520, 480, 400, 350, 300, 280],
};

// Weekly temperature outlook (°F)
const TEMP_OUTLOOK = {
  labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  high: [22, 26, 24, 20, 18, 16, 20],
  low:  [8,  12, 10,  4,  2,  0,  4],
};
