// ════════════════════════════════════════════════════════════
//  PowderTrack — Resort & Forecast Data
// ════════════════════════════════════════════════════════════

const RESORTS = [
  {
    id: 1,
    name: "Mammoth Mountain",
    region: "sierra",
    country: "USA",
    state: "CA",
    elevation: { base: 7953, summit: 11053 },
    base_in: 140,
    new48h_in: 14,
    forecast7d_in: 22,
    open_trails: 137,
    total_trails: 175,
    lifts_open: 22,
    lifts_total: 25,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 12,
    temp_f: 24,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { snow: 4,  high: 28, low: 14 },
      { snow: 8,  high: 22, low: 10 },
      { snow: 6,  high: 25, low: 12 },
      { snow: 2,  high: 30, low: 18 },
      { snow: 1,  high: 32, low: 20 },
      { snow: 0,  high: 35, low: 22 },
      { snow: 1,  high: 33, low: 21 },
    ],
    season_total_in: 382,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 06:00",
    lat: 37.631, lon: -119.032,
    webcam_url: "https://www.mammothmountain.com/on-the-mountain/mountain-report/webcams",
    trail_map_url: "https://www.mammothmountain.com/on-the-mountain/trail-maps",
  },
  {
    id: 2,
    name: "Park City Mountain",
    region: "wasatch",
    country: "USA",
    state: "UT",
    elevation: { base: 6900, summit: 10026 },
    base_in: 112,
    new48h_in: 10,
    forecast7d_in: 18,
    open_trails: 210,
    total_trails: 330,
    lifts_open: 34,
    lifts_total: 41,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 8,
    temp_f: 18,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 17, intermediate: 52, advanced: 31 },
    forecast: [
      { snow: 5,  high: 22, low: 8  },
      { snow: 7,  high: 20, low: 6  },
      { snow: 4,  high: 24, low: 10 },
      { snow: 2,  high: 28, low: 14 },
      { snow: 0,  high: 30, low: 16 },
      { snow: 3,  high: 26, low: 12 },
      { snow: 5,  high: 23, low: 9  },
    ],
    season_total_in: 298,
    avalanche_danger: "High",
    last_updated: "2026-02-26 06:30",
    lat: 40.651, lon: -111.508,
    webcam_url: "https://www.parkcitymountain.com/explore-the-resort/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.parkcitymountain.com/explore-the-resort/trail-map.aspx",
  },
  {
    id: 3,
    name: "Vail",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 8120, summit: 11570 },
    base_in: 86,
    new48h_in: 6,
    forecast7d_in: 14,
    open_trails: 185,
    total_trails: 195,
    lifts_open: 30,
    lifts_total: 31,
    rating: 4.7,
    surface: "Groomed",
    wind_mph: 15,
    temp_f: 20,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 18, intermediate: 29, advanced: 53 },
    forecast: [
      { snow: 2,  high: 24, low: 10 },
      { snow: 4,  high: 21, low: 8  },
      { snow: 5,  high: 22, low: 9  },
      { snow: 2,  high: 27, low: 14 },
      { snow: 1,  high: 30, low: 17 },
      { snow: 0,  high: 33, low: 19 },
      { snow: 2,  high: 28, low: 15 },
    ],
    season_total_in: 220,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 39.608, lon: -106.355,
    webcam_url: "https://www.vail.com/the-mountain/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.vail.com/the-mountain/trail-maps.aspx",
  },
  {
    id: 4,
    name: "Whistler Blackcomb",
    region: "cascades",
    country: "Canada",
    state: "BC",
    elevation: { base: 2182, summit: 7494 },
    base_in: 192,
    new48h_in: 8,
    forecast7d_in: 36,
    open_trails: 190,
    total_trails: 200,
    lifts_open: 36,
    lifts_total: 37,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 20,
    temp_f: 19,
    visibility: "Fair",
    groomed_today: false,
    status: "open",
    terrain: { beginner: 20, intermediate: 55, advanced: 25 },
    forecast: [
      { snow: 10, high: 22, low: 12 },
      { snow: 12, high: 20, low: 10 },
      { snow: 8,  high: 23, low: 13 },
      { snow: 4,  high: 26, low: 16 },
      { snow: 2,  high: 28, low: 18 },
      { snow: 6,  high: 24, low: 14 },
      { snow: 8,  high: 21, low: 11 },
    ],
    season_total_in: 450,
    avalanche_danger: "High",
    last_updated: "2026-02-26 05:00",
    lat: 50.116, lon: -122.948,
    webcam_url: "https://www.whistlerblackcomb.com/the-mountain/mountain-conditions/mountain-cams.aspx",
    trail_map_url: "https://www.whistlerblackcomb.com/the-mountain/about-the-mountain/trail-map.aspx",
  },
  {
    id: 5,
    name: "Telluride",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 8725, summit: 13150 },
    base_in: 95,
    new48h_in: 4,
    forecast7d_in: 10,
    open_trails: 143,
    total_trails: 148,
    lifts_open: 18,
    lifts_total: 19,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 18,
    temp_f: 16,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 23, intermediate: 36, advanced: 41 },
    forecast: [
      { snow: 1,  high: 20, low: 5  },
      { snow: 3,  high: 18, low: 3  },
      { snow: 4,  high: 19, low: 4  },
      { snow: 1,  high: 24, low: 10 },
      { snow: 0,  high: 28, low: 14 },
      { snow: 1,  high: 26, low: 12 },
      { snow: 2,  high: 23, low: 8  },
    ],
    season_total_in: 198,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:15",
    lat: 37.937, lon: -107.852,
    webcam_url: "https://www.telluride.com/mountain/mountain-report/webcams",
    trail_map_url: "https://www.telluride.com/mountain/trail-map",
  },
  {
    id: 6,
    name: "Chamonix Mont-Blanc",
    region: "alps",
    country: "France",
    state: "",
    elevation: { base: 3412, summit: 12605 },
    base_in: 98,
    new48h_in: 5,
    forecast7d_in: 16,
    open_trails: 40,
    total_trails: 44,
    lifts_open: 26,
    lifts_total: 28,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 22,
    temp_f: 14,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 12, intermediate: 38, advanced: 50 },
    forecast: [
      { snow: 3,  high: 16, low: 2  },
      { snow: 6,  high: 14, low: 0  },
      { snow: 4,  high: 16, low: 2  },
      { snow: 2,  high: 19, low: 5  },
      { snow: 1,  high: 21, low: 7  },
      { snow: 0,  high: 22, low: 8  },
      { snow: 3,  high: 18, low: 4  },
    ],
    season_total_in: 210,
    avalanche_danger: "High",
    last_updated: "2026-02-26 08:00",
    lat: 45.923, lon: 6.869,
    webcam_url: "https://www.chamonix.com/webcams,en,pg39.html",
    trail_map_url: "https://www.chamonix.com/skiing/ski-area-map,en,pg34.html",
  },
  {
    id: 7,
    name: "Niseko United",
    region: "japan",
    country: "Japan",
    state: "Hokkaido",
    elevation: { base: 820, summit: 4278 },
    base_in: 155,
    new48h_in: 12,
    forecast7d_in: 28,
    open_trails: 60,
    total_trails: 60,
    lifts_open: 30,
    lifts_total: 30,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 6,
    temp_f: 21,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 30, intermediate: 40, advanced: 30 },
    forecast: [
      { snow: 8,  high: 24, low: 14 },
      { snow: 6,  high: 22, low: 12 },
      { snow: 10, high: 20, low: 10 },
      { snow: 4,  high: 25, low: 15 },
      { snow: 2,  high: 27, low: 17 },
      { snow: 6,  high: 23, low: 13 },
      { snow: 8,  high: 21, low: 11 },
    ],
    season_total_in: 610,
    avalanche_danger: "Low",
    last_updated: "2026-02-26 04:00",
    lat: 42.797, lon: 140.688,
    webcam_url: "https://www.niseko.ne.jp/en/webcam/",
    trail_map_url: "https://www.niseko.ne.jp/en/ski-area/",
  },
  {
    id: 8,
    name: "Snowbird",
    region: "wasatch",
    country: "USA",
    state: "UT",
    elevation: { base: 7760, summit: 11000 },
    base_in: 130,
    new48h_in: 9,
    forecast7d_in: 20,
    open_trails: 127,
    total_trails: 139,
    lifts_open: 12,
    lifts_total: 13,
    rating: 4.7,
    surface: "Powder",
    wind_mph: 10,
    temp_f: 22,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 27, intermediate: 38, advanced: 35 },
    forecast: [
      { snow: 4,  high: 25, low: 12 },
      { snow: 8,  high: 21, low: 8  },
      { snow: 5,  high: 23, low: 10 },
      { snow: 2,  high: 27, low: 14 },
      { snow: 1,  high: 30, low: 17 },
      { snow: 0,  high: 32, low: 19 },
      { snow: 3,  high: 27, low: 13 },
    ],
    season_total_in: 340,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 06:45",
    lat: 40.583, lon: -111.656,
    webcam_url: "https://www.snowbird.com/mountain-report/",
    trail_map_url: "https://www.snowbird.com/mountain-report/trail-map/",
  },
  {
    id: 9,
    name: "Mt. Baker",
    region: "cascades",
    country: "USA",
    state: "WA",
    elevation: { base: 3500, summit: 5089 },
    base_in: 210,
    new48h_in: 14,
    forecast7d_in: 32,
    open_trails: 38,
    total_trails: 38,
    lifts_open: 10,
    lifts_total: 10,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 25,
    temp_f: 28,
    visibility: "Fair",
    groomed_today: false,
    status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { snow: 12, high: 30, low: 22 },
      { snow: 10, high: 28, low: 20 },
      { snow: 6,  high: 30, low: 22 },
      { snow: 4,  high: 32, low: 24 },
      { snow: 0,  high: 36, low: 26 },
      { snow: 2,  high: 34, low: 24 },
      { snow: 6,  high: 30, low: 22 },
    ],
    season_total_in: 520,
    avalanche_danger: "High",
    last_updated: "2026-02-26 06:00",
    lat: 48.858, lon: -121.679,
    webcam_url: "https://www.mtbaker.us/mountain-conditions/webcams/",
    trail_map_url: "https://www.mtbaker.us/the-mountain/trail-map/",
  },
  {
    id: 10,
    name: "Jackson Hole",
    region: "rockies",
    country: "USA",
    state: "WY",
    elevation: { base: 6311, summit: 10450 },
    base_in: 78,
    new48h_in: 3,
    forecast7d_in: 12,
    open_trails: 116,
    total_trails: 133,
    lifts_open: 13,
    lifts_total: 13,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 14,
    temp_f: 14,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 10, intermediate: 40, advanced: 50 },
    forecast: [
      { snow: 1,  high: 18, low: 2  },
      { snow: 4,  high: 16, low: 0  },
      { snow: 4,  high: 17, low: 1  },
      { snow: 2,  high: 22, low: 8  },
      { snow: 1,  high: 26, low: 12 },
      { snow: 0,  high: 28, low: 14 },
      { snow: 2,  high: 24, low: 10 },
    ],
    season_total_in: 182,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 43.588, lon: -110.828,
    webcam_url: "https://www.jacksonhole.com/web-cams.html",
    trail_map_url: "https://www.jacksonhole.com/trail-map.html",
  },
  {
    id: 11,
    name: "Palisades Tahoe",
    region: "sierra",
    country: "USA",
    state: "CA",
    elevation: { base: 6200, summit: 9050 },
    base_in: 118,
    new48h_in: 11,
    forecast7d_in: 18,
    open_trails: 170,
    total_trails: 178,
    lifts_open: 29,
    lifts_total: 30,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 16,
    temp_f: 26,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 25, intermediate: 45, advanced: 30 },
    forecast: [
      { snow: 3,  high: 28, low: 16 },
      { snow: 7,  high: 24, low: 12 },
      { snow: 5,  high: 26, low: 14 },
      { snow: 2,  high: 30, low: 18 },
      { snow: 1,  high: 33, low: 21 },
      { snow: 0,  high: 36, low: 23 },
      { snow: 2,  high: 31, low: 19 },
    ],
    season_total_in: 310,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 06:00",
    lat: 39.196, lon: -120.236,
    webcam_url: "https://www.palisadestahoe.com/mountain-info/mountain-conditions/webcams",
    trail_map_url: "https://www.palisadestahoe.com/mountain-info/trail-map",
  },
  {
    id: 12,
    name: "Zermatt",
    region: "alps",
    country: "Switzerland",
    state: "",
    elevation: { base: 5315, summit: 12533 },
    base_in: 72,
    new48h_in: 4,
    forecast7d_in: 10,
    open_trails: 52,
    total_trails: 52,
    lifts_open: 52,
    lifts_total: 52,
    rating: 4.9,
    surface: "Packed Powder",
    wind_mph: 12,
    temp_f: 10,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 22, intermediate: 38, advanced: 40 },
    forecast: [
      { snow: 2,  high: 14, low: -4 },
      { snow: 4,  high: 12, low: -6 },
      { snow: 2,  high: 13, low: -5 },
      { snow: 1,  high: 16, low: -2 },
      { snow: 0,  high: 18, low: 0  },
      { snow: 1,  high: 16, low: -2 },
      { snow: 3,  high: 14, low: -4 },
    ],
    season_total_in: 180,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 46.016, lon: 7.749,
    webcam_url: "https://www.zermatt.ch/en/Media/Webcams",
    trail_map_url: "https://www.zermatt.ch/en/Media/Maps/Piste-map",
  },
  {
    id: 13,
    name: "Aspen Snowmass",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 7945, summit: 12510 },
    base_in: 92,
    new48h_in: 7,
    forecast7d_in: 16,
    open_trails: 336,
    total_trails: 337,
    lifts_open: 40,
    lifts_total: 42,
    rating: 4.9,
    surface: "Packed Powder",
    wind_mph: 13,
    temp_f: 18,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 8, intermediate: 57, advanced: 35 },
    forecast: [
      { snow: 3,  high: 22, low: 8  },
      { snow: 5,  high: 20, low: 6  },
      { snow: 4,  high: 21, low: 7  },
      { snow: 2,  high: 25, low: 11 },
      { snow: 1,  high: 28, low: 14 },
      { snow: 0,  high: 31, low: 17 },
      { snow: 2,  high: 27, low: 13 },
    ],
    season_total_in: 215,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 39.208, lon: -106.946,
    webcam_url: "https://www.aspensnowmass.com/our-mountains/mountain-conditions/mountain-cams",
    trail_map_url: "https://www.aspensnowmass.com/our-mountains/trail-maps",
  },
  {
    id: 14,
    name: "Breckenridge",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 9600, summit: 13010 },
    base_in: 88,
    new48h_in: 5,
    forecast7d_in: 13,
    open_trails: 187,
    total_trails: 187,
    lifts_open: 30,
    lifts_total: 35,
    rating: 4.6,
    surface: "Groomed",
    wind_mph: 17,
    temp_f: 16,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 15, intermediate: 32, advanced: 53 },
    forecast: [
      { snow: 2,  high: 20, low: 4  },
      { snow: 4,  high: 18, low: 2  },
      { snow: 4,  high: 19, low: 3  },
      { snow: 2,  high: 23, low: 7  },
      { snow: 1,  high: 26, low: 10 },
      { snow: 0,  high: 29, low: 13 },
      { snow: 2,  high: 25, low: 9  },
    ],
    season_total_in: 192,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 39.481, lon: -106.066,
    webcam_url: "https://www.breckenridge.com/the-mountain/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.breckenridge.com/the-mountain/trail-maps.aspx",
  },
  {
    id: 15,
    name: "Stowe Mountain",
    region: "northeast",
    country: "USA",
    state: "VT",
    elevation: { base: 1559, summit: 4395 },
    base_in: 48,
    new48h_in: 6,
    forecast7d_in: 14,
    open_trails: 116,
    total_trails: 116,
    lifts_open: 13,
    lifts_total: 13,
    rating: 4.7,
    surface: "Packed Powder",
    wind_mph: 22,
    temp_f: 12,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 16, intermediate: 59, advanced: 25 },
    forecast: [
      { snow: 4,  high: 14, low: -2 },
      { snow: 6,  high: 12, low: -4 },
      { snow: 3,  high: 15, low: -1 },
      { snow: 1,  high: 20, low: 4  },
      { snow: 0,  high: 24, low: 8  },
      { snow: 2,  high: 21, low: 5  },
      { snow: 4,  high: 16, low: 0  },
    ],
    season_total_in: 142,
    avalanche_danger: "Low",
    last_updated: "2026-02-26 07:00",
    lat: 44.530, lon: -72.782,
    webcam_url: "https://www.stowe.com/the-mountain/mountain-conditions/webcams.aspx",
    trail_map_url: "https://www.stowe.com/the-mountain/trail-maps.aspx",
  },
  {
    id: 16,
    name: "Killington",
    region: "northeast",
    country: "USA",
    state: "VT",
    elevation: { base: 1165, summit: 4241 },
    base_in: 52,
    new48h_in: 8,
    forecast7d_in: 16,
    open_trails: 155,
    total_trails: 155,
    lifts_open: 22,
    lifts_total: 22,
    rating: 4.5,
    surface: "Packed Powder",
    wind_mph: 19,
    temp_f: 10,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 28, intermediate: 33, advanced: 39 },
    forecast: [
      { snow: 5,  high: 12, low: -4 },
      { snow: 7,  high: 10, low: -6 },
      { snow: 4,  high: 13, low: -3 },
      { snow: 2,  high: 18, low: 2  },
      { snow: 0,  high: 22, low: 6  },
      { snow: 3,  high: 19, low: 3  },
      { snow: 5,  high: 14, low: -2 },
    ],
    season_total_in: 168,
    avalanche_danger: "Low",
    last_updated: "2026-02-26 07:00",
    lat: 43.623, lon: -72.820,
    webcam_url: "https://www.killington.com/the-mountain/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.killington.com/the-mountain/trail-maps.aspx",
  },
  {
    id: 17,
    name: "Val d'Isère",
    region: "alps",
    country: "France",
    state: "",
    elevation: { base: 5905, summit: 11483 },
    base_in: 84,
    new48h_in: 6,
    forecast7d_in: 18,
    open_trails: 150,
    total_trails: 154,
    lifts_open: 78,
    lifts_total: 80,
    rating: 4.8,
    surface: "Powder",
    wind_mph: 20,
    temp_f: 8,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 15, intermediate: 40, advanced: 45 },
    forecast: [
      { snow: 4,  high: 10, low: -8 },
      { snow: 7,  high: 8,  low: -10 },
      { snow: 5,  high: 10, low: -8 },
      { snow: 2,  high: 14, low: -4 },
      { snow: 1,  high: 17, low: -1 },
      { snow: 0,  high: 18, low: 0  },
      { snow: 3,  high: 13, low: -5 },
    ],
    season_total_in: 188,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 08:00",
    lat: 45.448, lon: 6.977,
    webcam_url: "https://www.valdisere.com/en/webcams/",
    trail_map_url: "https://www.valdisere.com/en/ski-area/",
  },
  {
    id: 18,
    name: "Verbier",
    region: "alps",
    country: "Switzerland",
    state: "",
    elevation: { base: 4921, summit: 10925 },
    base_in: 68,
    new48h_in: 3,
    forecast7d_in: 12,
    open_trails: 92,
    total_trails: 92,
    lifts_open: 37,
    lifts_total: 38,
    rating: 4.7,
    surface: "Packed Powder",
    wind_mph: 14,
    temp_f: 12,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 10, intermediate: 40, advanced: 50 },
    forecast: [
      { snow: 2,  high: 16, low: -2 },
      { snow: 4,  high: 14, low: -4 },
      { snow: 3,  high: 15, low: -3 },
      { snow: 1,  high: 18, low: 0  },
      { snow: 0,  high: 21, low: 3  },
      { snow: 1,  high: 19, low: 1  },
      { snow: 2,  high: 16, low: -2 },
    ],
    season_total_in: 162,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 08:00",
    lat: 46.096, lon: 7.229,
    webcam_url: "https://www.verbier.ch/en/webcams/",
    trail_map_url: "https://www.verbier.ch/en/ski-area/piste-map/",
  },
  {
    id: 19,
    name: "Cortina d'Ampezzo",
    region: "alps",
    country: "Italy",
    state: "",
    elevation: { base: 4003, summit: 10479 },
    base_in: 55,
    new48h_in: 3,
    forecast7d_in: 9,
    open_trails: 120,
    total_trails: 120,
    lifts_open: 35,
    lifts_total: 37,
    rating: 4.6,
    surface: "Groomed",
    wind_mph: 10,
    temp_f: 16,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 20, intermediate: 50, advanced: 30 },
    forecast: [
      { snow: 1,  high: 18, low: 2  },
      { snow: 3,  high: 16, low: 0  },
      { snow: 3,  high: 17, low: 1  },
      { snow: 1,  high: 21, low: 5  },
      { snow: 0,  high: 24, low: 8  },
      { snow: 1,  high: 22, low: 6  },
      { snow: 2,  high: 18, low: 2  },
    ],
    season_total_in: 138,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 46.540, lon: 12.135,
    webcam_url: "https://www.dolomiti.org/en/cortina/webcam/",
    trail_map_url: "https://www.cortina.dolomiti.org/en/ski-area/",
  },
  {
    id: 20,
    name: "Sun Valley",
    region: "rockies",
    country: "USA",
    state: "ID",
    elevation: { base: 5750, summit: 9150 },
    base_in: 74,
    new48h_in: 4,
    forecast7d_in: 11,
    open_trails: 121,
    total_trails: 121,
    lifts_open: 18,
    lifts_total: 18,
    rating: 4.6,
    surface: "Packed Powder",
    wind_mph: 11,
    temp_f: 20,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 36, intermediate: 42, advanced: 22 },
    forecast: [
      { snow: 2,  high: 24, low: 8  },
      { snow: 3,  high: 21, low: 5  },
      { snow: 3,  high: 22, low: 6  },
      { snow: 2,  high: 27, low: 11 },
      { snow: 1,  high: 30, low: 14 },
      { snow: 0,  high: 32, low: 16 },
      { snow: 1,  high: 28, low: 12 },
    ],
    season_total_in: 175,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 43.696, lon: -114.351,
    webcam_url: "https://www.sunvalley.com/discover/webcams/",
    trail_map_url: "https://www.sunvalley.com/mountain/trail-map/",
  },
];

// Season snowfall comparison data
const SEASON_DATA = {
  labels: ["Niseko", "Mt. Baker", "Whistler", "Mammoth", "Snowbird", "Palisades"],
  current: [610, 520, 450, 382, 340, 310],
  avg: [520, 480, 400, 350, 300, 280],
};

// Weekly temperature outlook (°F)
const TEMP_OUTLOOK = {
  labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  high: [22, 26, 24, 20, 18, 16, 20],
  low:  [8,  12, 10,  4,  2,  0,  4],
};
