// ════════════════════════════════════════════════════════════
//  PowderTrack — Resort & Forecast Data
// ════════════════════════════════════════════════════════════

const RESORTS = [
  {
    id: 1,
    name: "Mammoth Mountain",
    region: "sierra",
    country: "USA",
    state: "CA",
    elevation: { base: 7953, summit: 11053 },
    base_in: 140,
    new48h_in: 14,
    forecast7d_in: 22,
    open_trails: 137,
    total_trails: 175,
    lifts_open: 22,
    lifts_total: 25,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 12,
    temp_f: 24,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { snow: 4,  high: 28, low: 14 },
      { snow: 8,  high: 22, low: 10 },
      { snow: 6,  high: 25, low: 12 },
      { snow: 2,  high: 30, low: 18 },
      { snow: 1,  high: 32, low: 20 },
      { snow: 0,  high: 35, low: 22 },
      { snow: 1,  high: 33, low: 21 },
    ],
    season_total_in: 382,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 06:00",
    lat: 37.631, lon: -119.032,
    webcam_url: "https://www.mammothmountain.com/on-the-mountain/mountain-report/webcams",
    trail_map_url: "https://www.mammothmountain.com/on-the-mountain/trail-maps",
    trail_map_pdf_url: "https://images.ski.com/docs/trail-maps/mammoth_trail-map.pdf",
  },
  {
    id: 2,
    name: "Park City Mountain",
    region: "wasatch",
    country: "USA",
    state: "UT",
    elevation: { base: 6900, summit: 10026 },
    base_in: 112,
    new48h_in: 10,
    forecast7d_in: 18,
    open_trails: 210,
    total_trails: 330,
    lifts_open: 34,
    lifts_total: 41,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 8,
    temp_f: 18,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 17, intermediate: 52, advanced: 31 },
    forecast: [
      { snow: 5,  high: 22, low: 8  },
      { snow: 7,  high: 20, low: 6  },
      { snow: 4,  high: 24, low: 10 },
      { snow: 2,  high: 28, low: 14 },
      { snow: 0,  high: 30, low: 16 },
      { snow: 3,  high: 26, low: 12 },
      { snow: 5,  high: 23, low: 9  },
    ],
    season_total_in: 298,
    avalanche_danger: "High",
    last_updated: "2026-02-26 06:30",
    lat: 40.651, lon: -111.508,
    webcam_url: "https://www.parkcitymountain.com/explore-the-resort/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.parkcitymountain.com/explore-the-resort/trail-map.aspx",
    trail_map_pdf_url: "https://www.parkcitymountain.com/-/aemasset/sitecore/park-city/maps/20251114_PC_winter-trail_map_001.pdf",
  },
  {
    id: 3,
    name: "Vail",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 8120, summit: 11570 },
    base_in: 86,
    new48h_in: 6,
    forecast7d_in: 14,
    open_trails: 185,
    total_trails: 195,
    lifts_open: 30,
    lifts_total: 31,
    rating: 4.7,
    surface: "Groomed",
    wind_mph: 15,
    temp_f: 20,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 18, intermediate: 29, advanced: 53 },
    forecast: [
      { snow: 2,  high: 24, low: 10 },
      { snow: 4,  high: 21, low: 8  },
      { snow: 5,  high: 22, low: 9  },
      { snow: 2,  high: 27, low: 14 },
      { snow: 1,  high: 30, low: 17 },
      { snow: 0,  high: 33, low: 19 },
      { snow: 2,  high: 28, low: 15 },
    ],
    season_total_in: 220,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 39.608, lon: -106.355,
    webcam_url: "https://www.vail.com/the-mountain/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.vail.com/the-mountain/trail-maps.aspx",
    trail_map_pdf_url: "https://images.ski.com/docs/trail-maps/vail-frontside_trail-map.pdf",
  },
  {
    id: 4,
    name: "Whistler Blackcomb",
    region: "cascades",
    country: "Canada",
    state: "BC",
    elevation: { base: 2182, summit: 7494 },
    base_in: 192,
    new48h_in: 8,
    forecast7d_in: 36,
    open_trails: 190,
    total_trails: 200,
    lifts_open: 36,
    lifts_total: 37,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 20,
    temp_f: 19,
    visibility: "Fair",
    groomed_today: false,
    status: "open",
    terrain: { beginner: 20, intermediate: 55, advanced: 25 },
    forecast: [
      { snow: 10, high: 22, low: 12 },
      { snow: 12, high: 20, low: 10 },
      { snow: 8,  high: 23, low: 13 },
      { snow: 4,  high: 26, low: 16 },
      { snow: 2,  high: 28, low: 18 },
      { snow: 6,  high: 24, low: 14 },
      { snow: 8,  high: 21, low: 11 },
    ],
    season_total_in: 450,
    avalanche_danger: "High",
    last_updated: "2026-02-26 05:00",
    lat: 50.116, lon: -122.948,
    webcam_url: "https://www.whistlerblackcomb.com/the-mountain/mountain-conditions/mountain-cams.aspx",
    trail_map_url: "https://www.whistlerblackcomb.com/the-mountain/about-the-mountain/trail-map.aspx",
    trail_map_pdf_url: "https://www.whistlerblackcomb.com/-/aemasset/sitecore/whistler-blackcomb/maps/winter-2024-2025/20241115_WB_winter-trail_map_001.pdf",
  },
  {
    id: 5,
    name: "Telluride",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 8725, summit: 13150 },
    base_in: 95,
    new48h_in: 4,
    forecast7d_in: 10,
    open_trails: 143,
    total_trails: 148,
    lifts_open: 18,
    lifts_total: 19,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 18,
    temp_f: 16,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 23, intermediate: 36, advanced: 41 },
    forecast: [
      { snow: 1,  high: 20, low: 5  },
      { snow: 3,  high: 18, low: 3  },
      { snow: 4,  high: 19, low: 4  },
      { snow: 1,  high: 24, low: 10 },
      { snow: 0,  high: 28, low: 14 },
      { snow: 1,  high: 26, low: 12 },
      { snow: 2,  high: 23, low: 8  },
    ],
    season_total_in: 198,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:15",
    lat: 37.937, lon: -107.852,
    webcam_url: "https://www.telluride.com/mountain/mountain-report/webcams",
    trail_map_url: "https://www.telluride.com/mountain/trail-map",
    trail_map_pdf_url: "https://images.ski.com/docs/trail-maps/telluride_trail-map.pdf",
  },
  {
    id: 6,
    name: "Chamonix Mont-Blanc",
    region: "alps",
    country: "France",
    state: "",
    elevation: { base: 3412, summit: 12605 },
    base_in: 98,
    new48h_in: 5,
    forecast7d_in: 16,
    open_trails: 40,
    total_trails: 44,
    lifts_open: 26,
    lifts_total: 28,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 22,
    temp_f: 14,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 12, intermediate: 38, advanced: 50 },
    forecast: [
      { snow: 3,  high: 16, low: 2  },
      { snow: 6,  high: 14, low: 0  },
      { snow: 4,  high: 16, low: 2  },
      { snow: 2,  high: 19, low: 5  },
      { snow: 1,  high: 21, low: 7  },
      { snow: 0,  high: 22, low: 8  },
      { snow: 3,  high: 18, low: 4  },
    ],
    season_total_in: 210,
    avalanche_danger: "High",
    last_updated: "2026-02-26 08:00",
    lat: 45.923, lon: 6.869,
    webcam_url: "https://www.chamonix.com/webcams,en,pg39.html",
    trail_map_url: "https://www.chamonix.com/skiing/ski-area-map,en,pg34.html",
    trail_map_pdf_url: "",
  },
  {
    id: 7,
    name: "Niseko United",
    region: "japan",
    country: "Japan",
    state: "Hokkaido",
    elevation: { base: 820, summit: 4278 },
    base_in: 155,
    new48h_in: 12,
    forecast7d_in: 28,
    open_trails: 60,
    total_trails: 60,
    lifts_open: 30,
    lifts_total: 30,
    rating: 4.9,
    surface: "Powder",
    wind_mph: 6,
    temp_f: 21,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 30, intermediate: 40, advanced: 30 },
    forecast: [
      { snow: 8,  high: 24, low: 14 },
      { snow: 6,  high: 22, low: 12 },
      { snow: 10, high: 20, low: 10 },
      { snow: 4,  high: 25, low: 15 },
      { snow: 2,  high: 27, low: 17 },
      { snow: 6,  high: 23, low: 13 },
      { snow: 8,  high: 21, low: 11 },
    ],
    season_total_in: 610,
    avalanche_danger: "Low",
    last_updated: "2026-02-26 04:00",
    lat: 42.797, lon: 140.688,
    webcam_url: "https://www.niseko.ne.jp/en/webcam/",
    trail_map_url: "https://www.niseko.ne.jp/en/ski-area/",
    trail_map_pdf_url: "https://www.niseko.ne.jp/en/wp-content/uploads/2020/08/2025-2026_WEBMAP_EG.pdf",
  },
  {
    id: 8,
    name: "Snowbird",
    region: "wasatch",
    country: "USA",
    state: "UT",
    elevation: { base: 7760, summit: 11000 },
    base_in: 130,
    new48h_in: 9,
    forecast7d_in: 20,
    open_trails: 127,
    total_trails: 139,
    lifts_open: 12,
    lifts_total: 13,
    rating: 4.7,
    surface: "Powder",
    wind_mph: 10,
    temp_f: 22,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 27, intermediate: 38, advanced: 35 },
    forecast: [
      { snow: 4,  high: 25, low: 12 },
      { snow: 8,  high: 21, low: 8  },
      { snow: 5,  high: 23, low: 10 },
      { snow: 2,  high: 27, low: 14 },
      { snow: 1,  high: 30, low: 17 },
      { snow: 0,  high: 32, low: 19 },
      { snow: 3,  high: 27, low: 13 },
    ],
    season_total_in: 340,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 06:45",
    lat: 40.583, lon: -111.656,
    webcam_url: "https://www.snowbird.com/mountain-report/",
    trail_map_url: "https://www.snowbird.com/mountain-report/trail-map/",
    trail_map_pdf_url: "https://www.altalodge.com/wp-content/uploads/2023/08/snowbird_wintertrailmap_web-1.pdf",
  },
  {
    id: 9,
    name: "Mt. Baker",
    region: "cascades",
    country: "USA",
    state: "WA",
    elevation: { base: 3500, summit: 5089 },
    base_in: 210,
    new48h_in: 14,
    forecast7d_in: 32,
    open_trails: 38,
    total_trails: 38,
    lifts_open: 10,
    lifts_total: 10,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 25,
    temp_f: 28,
    visibility: "Fair",
    groomed_today: false,
    status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { snow: 12, high: 30, low: 22 },
      { snow: 10, high: 28, low: 20 },
      { snow: 6,  high: 30, low: 22 },
      { snow: 4,  high: 32, low: 24 },
      { snow: 0,  high: 36, low: 26 },
      { snow: 2,  high: 34, low: 24 },
      { snow: 6,  high: 30, low: 22 },
    ],
    season_total_in: 520,
    avalanche_danger: "High",
    last_updated: "2026-02-26 06:00",
    lat: 48.858, lon: -121.679,
    webcam_url: "https://www.mtbaker.us/mountain-conditions/webcams/",
    trail_map_url: "https://www.mtbaker.us/the-mountain/trail-map/",
    trail_map_pdf_url: "https://www.mtbaker.us/wp-content/uploads/2024/11/Trail-Map-for-Website_24-25.pdf",
  },
  {
    id: 10,
    name: "Jackson Hole",
    region: "rockies",
    country: "USA",
    state: "WY",
    elevation: { base: 6311, summit: 10450 },
    base_in: 78,
    new48h_in: 3,
    forecast7d_in: 12,
    open_trails: 116,
    total_trails: 133,
    lifts_open: 13,
    lifts_total: 13,
    rating: 4.8,
    surface: "Packed Powder",
    wind_mph: 14,
    temp_f: 14,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 10, intermediate: 40, advanced: 50 },
    forecast: [
      { snow: 1,  high: 18, low: 2  },
      { snow: 4,  high: 16, low: 0  },
      { snow: 4,  high: 17, low: 1  },
      { snow: 2,  high: 22, low: 8  },
      { snow: 1,  high: 26, low: 12 },
      { snow: 0,  high: 28, low: 14 },
      { snow: 2,  high: 24, low: 10 },
    ],
    season_total_in: 182,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 43.588, lon: -110.828,
    webcam_url: "https://www.jacksonhole.com/web-cams.html",
    trail_map_url: "https://www.jacksonhole.com/trail-map.html",
    trail_map_pdf_url: "https://images.ski.com/docs/trail-maps/jacksonhole_trail-map.pdf",
  },
  {
    id: 11,
    name: "Palisades Tahoe",
    region: "sierra",
    country: "USA",
    state: "CA",
    elevation: { base: 6200, summit: 9050 },
    base_in: 118,
    new48h_in: 11,
    forecast7d_in: 18,
    open_trails: 170,
    total_trails: 178,
    lifts_open: 29,
    lifts_total: 30,
    rating: 4.6,
    surface: "Powder",
    wind_mph: 16,
    temp_f: 26,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 25, intermediate: 45, advanced: 30 },
    forecast: [
      { snow: 3,  high: 28, low: 16 },
      { snow: 7,  high: 24, low: 12 },
      { snow: 5,  high: 26, low: 14 },
      { snow: 2,  high: 30, low: 18 },
      { snow: 1,  high: 33, low: 21 },
      { snow: 0,  high: 36, low: 23 },
      { snow: 2,  high: 31, low: 19 },
    ],
    season_total_in: 310,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 06:00",
    lat: 39.196, lon: -120.236,
    webcam_url: "https://www.palisadestahoe.com/mountain-info/mountain-conditions/webcams",
    trail_map_url: "https://www.palisadestahoe.com/mountain-info/trail-map",
    trail_map_pdf_url: "https://www.palisadestahoe.com/-/media/palisades-tahoe/pdfs/trail-maps/palisadesmaintrailmap.pdf",
  },
  {
    id: 12,
    name: "Zermatt",
    region: "alps",
    country: "Switzerland",
    state: "",
    elevation: { base: 5315, summit: 12533 },
    base_in: 72,
    new48h_in: 4,
    forecast7d_in: 10,
    open_trails: 52,
    total_trails: 52,
    lifts_open: 52,
    lifts_total: 52,
    rating: 4.9,
    surface: "Packed Powder",
    wind_mph: 12,
    temp_f: 10,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 22, intermediate: 38, advanced: 40 },
    forecast: [
      { snow: 2,  high: 14, low: -4 },
      { snow: 4,  high: 12, low: -6 },
      { snow: 2,  high: 13, low: -5 },
      { snow: 1,  high: 16, low: -2 },
      { snow: 0,  high: 18, low: 0  },
      { snow: 1,  high: 16, low: -2 },
      { snow: 3,  high: 14, low: -4 },
    ],
    season_total_in: 180,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 46.016, lon: 7.749,
    webcam_url: "https://www.zermatt.ch/en/Media/Webcams",
    trail_map_url: "https://www.zermatt.ch/en/Media/Maps/Piste-map",
    trail_map_pdf_url: "https://www.allchalets.com/system/cms/files/38/files/original/zermatt-piste-map.pdf",
  },
  {
    id: 13,
    name: "Aspen Snowmass",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 7945, summit: 12510 },
    base_in: 92,
    new48h_in: 7,
    forecast7d_in: 16,
    open_trails: 336,
    total_trails: 337,
    lifts_open: 40,
    lifts_total: 42,
    rating: 4.9,
    surface: "Packed Powder",
    wind_mph: 13,
    temp_f: 18,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 8, intermediate: 57, advanced: 35 },
    forecast: [
      { snow: 3,  high: 22, low: 8  },
      { snow: 5,  high: 20, low: 6  },
      { snow: 4,  high: 21, low: 7  },
      { snow: 2,  high: 25, low: 11 },
      { snow: 1,  high: 28, low: 14 },
      { snow: 0,  high: 31, low: 17 },
      { snow: 2,  high: 27, low: 13 },
    ],
    season_total_in: 215,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 39.208, lon: -106.946,
    webcam_url: "https://www.aspensnowmass.com/our-mountains/mountain-conditions/mountain-cams",
    trail_map_url: "https://www.aspensnowmass.com/our-mountains/trail-maps",
    trail_map_pdf_url: "https://images.ski.com/docs/trail-maps/snowmass_trail-map.pdf",
  },
  {
    id: 14,
    name: "Breckenridge",
    region: "rockies",
    country: "USA",
    state: "CO",
    elevation: { base: 9600, summit: 13010 },
    base_in: 88,
    new48h_in: 5,
    forecast7d_in: 13,
    open_trails: 187,
    total_trails: 187,
    lifts_open: 30,
    lifts_total: 35,
    rating: 4.6,
    surface: "Groomed",
    wind_mph: 17,
    temp_f: 16,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 15, intermediate: 32, advanced: 53 },
    forecast: [
      { snow: 2,  high: 20, low: 4  },
      { snow: 4,  high: 18, low: 2  },
      { snow: 4,  high: 19, low: 3  },
      { snow: 2,  high: 23, low: 7  },
      { snow: 1,  high: 26, low: 10 },
      { snow: 0,  high: 29, low: 13 },
      { snow: 2,  high: 25, low: 9  },
    ],
    season_total_in: 192,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 39.481, lon: -106.066,
    webcam_url: "https://www.breckenridge.com/the-mountain/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.breckenridge.com/the-mountain/trail-maps.aspx",
    trail_map_pdf_url: "https://www.breckenridge.com/-/aemasset/sitecore/breckenridge/maps/20231031_BR_winter-trail_map_001.pdf",
  },
  {
    id: 15,
    name: "Stowe Mountain",
    region: "northeast",
    country: "USA",
    state: "VT",
    elevation: { base: 1559, summit: 4395 },
    base_in: 48,
    new48h_in: 6,
    forecast7d_in: 14,
    open_trails: 116,
    total_trails: 116,
    lifts_open: 13,
    lifts_total: 13,
    rating: 4.7,
    surface: "Packed Powder",
    wind_mph: 22,
    temp_f: 12,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 16, intermediate: 59, advanced: 25 },
    forecast: [
      { snow: 4,  high: 14, low: -2 },
      { snow: 6,  high: 12, low: -4 },
      { snow: 3,  high: 15, low: -1 },
      { snow: 1,  high: 20, low: 4  },
      { snow: 0,  high: 24, low: 8  },
      { snow: 2,  high: 21, low: 5  },
      { snow: 4,  high: 16, low: 0  },
    ],
    season_total_in: 142,
    avalanche_danger: "Low",
    last_updated: "2026-02-26 07:00",
    lat: 44.530, lon: -72.782,
    webcam_url: "https://www.stowe.com/the-mountain/mountain-conditions/webcams.aspx",
    trail_map_url: "https://www.stowe.com/the-mountain/trail-maps.aspx",
    trail_map_pdf_url: "https://www.stowe.com/-/aemasset/sitecore/stowe/maps/winter-2025-2026/20251014_ST_winter-trail_map_001.pdf",
  },
  {
    id: 16,
    name: "Killington",
    region: "northeast",
    country: "USA",
    state: "VT",
    elevation: { base: 1165, summit: 4241 },
    base_in: 52,
    new48h_in: 8,
    forecast7d_in: 16,
    open_trails: 155,
    total_trails: 155,
    lifts_open: 22,
    lifts_total: 22,
    rating: 4.5,
    surface: "Packed Powder",
    wind_mph: 19,
    temp_f: 10,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 28, intermediate: 33, advanced: 39 },
    forecast: [
      { snow: 5,  high: 12, low: -4 },
      { snow: 7,  high: 10, low: -6 },
      { snow: 4,  high: 13, low: -3 },
      { snow: 2,  high: 18, low: 2  },
      { snow: 0,  high: 22, low: 6  },
      { snow: 3,  high: 19, low: 3  },
      { snow: 5,  high: 14, low: -2 },
    ],
    season_total_in: 168,
    avalanche_danger: "Low",
    last_updated: "2026-02-26 07:00",
    lat: 43.623, lon: -72.820,
    webcam_url: "https://www.killington.com/the-mountain/mountain-conditions/web-cams.aspx",
    trail_map_url: "https://www.killington.com/the-mountain/trail-maps.aspx",
    trail_map_pdf_url: "https://images.ski.com/docs/trail-maps/killington_trail-map.pdf",
  },
  {
    id: 17,
    name: "Val d'Isère",
    region: "alps",
    country: "France",
    state: "",
    elevation: { base: 5905, summit: 11483 },
    base_in: 84,
    new48h_in: 6,
    forecast7d_in: 18,
    open_trails: 150,
    total_trails: 154,
    lifts_open: 78,
    lifts_total: 80,
    rating: 4.8,
    surface: "Powder",
    wind_mph: 20,
    temp_f: 8,
    visibility: "Good",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 15, intermediate: 40, advanced: 45 },
    forecast: [
      { snow: 4,  high: 10, low: -8 },
      { snow: 7,  high: 8,  low: -10 },
      { snow: 5,  high: 10, low: -8 },
      { snow: 2,  high: 14, low: -4 },
      { snow: 1,  high: 17, low: -1 },
      { snow: 0,  high: 18, low: 0  },
      { snow: 3,  high: 13, low: -5 },
    ],
    season_total_in: 188,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 08:00",
    lat: 45.448, lon: 6.977,
    webcam_url: "https://www.valdisere.com/en/webcams/",
    trail_map_url: "https://www.valdisere.com/en/ski-area/",
    trail_map_pdf_url: "",
  },
  {
    id: 18,
    name: "Verbier",
    region: "alps",
    country: "Switzerland",
    state: "",
    elevation: { base: 4921, summit: 10925 },
    base_in: 68,
    new48h_in: 3,
    forecast7d_in: 12,
    open_trails: 92,
    total_trails: 92,
    lifts_open: 37,
    lifts_total: 38,
    rating: 4.7,
    surface: "Packed Powder",
    wind_mph: 14,
    temp_f: 12,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 10, intermediate: 40, advanced: 50 },
    forecast: [
      { snow: 2,  high: 16, low: -2 },
      { snow: 4,  high: 14, low: -4 },
      { snow: 3,  high: 15, low: -3 },
      { snow: 1,  high: 18, low: 0  },
      { snow: 0,  high: 21, low: 3  },
      { snow: 1,  high: 19, low: 1  },
      { snow: 2,  high: 16, low: -2 },
    ],
    season_total_in: 162,
    avalanche_danger: "Considerable",
    last_updated: "2026-02-26 08:00",
    lat: 46.096, lon: 7.229,
    webcam_url: "https://www.verbier.ch/en/webcams/",
    trail_map_url: "https://www.verbier.ch/en/ski-area/piste-map/",
    trail_map_pdf_url: "",
  },
  {
    id: 19,
    name: "Cortina d'Ampezzo",
    region: "alps",
    country: "Italy",
    state: "",
    elevation: { base: 4003, summit: 10479 },
    base_in: 55,
    new48h_in: 3,
    forecast7d_in: 9,
    open_trails: 120,
    total_trails: 120,
    lifts_open: 35,
    lifts_total: 37,
    rating: 4.6,
    surface: "Groomed",
    wind_mph: 10,
    temp_f: 16,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 20, intermediate: 50, advanced: 30 },
    forecast: [
      { snow: 1,  high: 18, low: 2  },
      { snow: 3,  high: 16, low: 0  },
      { snow: 3,  high: 17, low: 1  },
      { snow: 1,  high: 21, low: 5  },
      { snow: 0,  high: 24, low: 8  },
      { snow: 1,  high: 22, low: 6  },
      { snow: 2,  high: 18, low: 2  },
    ],
    season_total_in: 138,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 46.540, lon: 12.135,
    webcam_url: "https://www.dolomiti.org/en/cortina/webcam/",
    trail_map_url: "https://www.cortina.dolomiti.org/en/ski-area/",
    trail_map_pdf_url: "",
  },
  {
    id: 20,
    name: "Sun Valley",
    region: "rockies",
    country: "USA",
    state: "ID",
    elevation: { base: 5750, summit: 9150 },
    base_in: 74,
    new48h_in: 4,
    forecast7d_in: 11,
    open_trails: 121,
    total_trails: 121,
    lifts_open: 18,
    lifts_total: 18,
    rating: 4.6,
    surface: "Packed Powder",
    wind_mph: 11,
    temp_f: 20,
    visibility: "Excellent",
    groomed_today: true,
    status: "open",
    terrain: { beginner: 36, intermediate: 42, advanced: 22 },
    forecast: [
      { snow: 2,  high: 24, low: 8  },
      { snow: 3,  high: 21, low: 5  },
      { snow: 3,  high: 22, low: 6  },
      { snow: 2,  high: 27, low: 11 },
      { snow: 1,  high: 30, low: 14 },
      { snow: 0,  high: 32, low: 16 },
      { snow: 1,  high: 28, low: 12 },
    ],
    season_total_in: 175,
    avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 43.696, lon: -114.351,
    webcam_url: "https://www.sunvalley.com/discover/webcams/",
    trail_map_url: "https://www.sunvalley.com/mountain/trail-map/",
    trail_map_pdf_url: "https://scoutski.com/assets/uploads/image/article/587/Sun%20Valley%20Ski%20Resort%20Trail%20Map_1.pdf",
  },

  // ── Sierra ──────────────────────────────────────────────
  {
    id: 21, name: "Heavenly", region: "sierra", country: "USA", state: "CA",
    elevation: { base: 6540, summit: 10067 },
    base_in: 60, new48h_in: 4, forecast7d_in: 10,
    open_trails: 97, total_trails: 97, lifts_open: 28, lifts_total: 28,
    rating: 4.5, surface: "Packed Powder", wind_mph: 15, temp_f: 28,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 20, intermediate: 45, advanced: 35 },
    forecast: [
      { snow: 2, high: 30, low: 14 }, { snow: 3, high: 28, low: 12 },
      { snow: 2, high: 29, low: 13 }, { snow: 1, high: 33, low: 17 },
      { snow: 0, high: 36, low: 20 }, { snow: 1, high: 34, low: 18 },
      { snow: 1, high: 31, low: 15 },
    ],
    season_total_in: 230, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 38.935, lon: -119.940,
    webcam_url: "https://www.skiheavenly.com/the-mountain/mountain-conditions/webcams.aspx",
    trail_map_url: "https://www.skiheavenly.com/the-mountain/trail-map.aspx",
    trail_map_pdf_url: "",
  },
  {
    id: 22, name: "Sugar Bowl", region: "sierra", country: "USA", state: "CA",
    elevation: { base: 6883, summit: 8383 },
    base_in: 90, new48h_in: 6, forecast7d_in: 14,
    open_trails: 103, total_trails: 103, lifts_open: 12, lifts_total: 13,
    rating: 4.5, surface: "Powder", wind_mph: 12, temp_f: 24,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 17, intermediate: 45, advanced: 38 },
    forecast: [
      { snow: 3, high: 26, low: 10 }, { snow: 4, high: 24, low: 8 },
      { snow: 3, high: 25, low: 9 }, { snow: 2, high: 29, low: 13 },
      { snow: 1, high: 32, low: 16 }, { snow: 0, high: 34, low: 18 },
      { snow: 1, high: 30, low: 14 },
    ],
    season_total_in: 310, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 39.305, lon: -120.366,
    webcam_url: "https://www.sugarbowl.com/conditions",
    trail_map_url: "https://www.sugarbowl.com/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 23, name: "Kirkwood", region: "sierra", country: "USA", state: "CA",
    elevation: { base: 7800, summit: 9800 },
    base_in: 95, new48h_in: 7, forecast7d_in: 16,
    open_trails: 86, total_trails: 86, lifts_open: 12, lifts_total: 15,
    rating: 4.6, surface: "Powder", wind_mph: 14, temp_f: 22,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 12, intermediate: 30, advanced: 58 },
    forecast: [
      { snow: 4, high: 24, low: 8 }, { snow: 5, high: 22, low: 6 },
      { snow: 3, high: 23, low: 7 }, { snow: 2, high: 27, low: 11 },
      { snow: 1, high: 30, low: 14 }, { snow: 0, high: 32, low: 16 },
      { snow: 1, high: 28, low: 12 },
    ],
    season_total_in: 340, avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 38.685, lon: -120.065,
    webcam_url: "https://www.kirkwood.com/the-mountain/mountain-conditions/webcams.aspx",
    trail_map_url: "https://www.kirkwood.com/the-mountain/trail-map.aspx",
    trail_map_pdf_url: "",
  },
  {
    id: 24, name: "Sierra at Tahoe", region: "sierra", country: "USA", state: "CA",
    elevation: { base: 6640, summit: 8852 },
    base_in: 65, new48h_in: 3, forecast7d_in: 8,
    open_trails: 46, total_trails: 46, lifts_open: 10, lifts_total: 14,
    rating: 4.3, surface: "Packed Powder", wind_mph: 10, temp_f: 26,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 25, intermediate: 50, advanced: 25 },
    forecast: [
      { snow: 1, high: 28, low: 12 }, { snow: 2, high: 26, low: 10 },
      { snow: 2, high: 27, low: 11 }, { snow: 1, high: 31, low: 15 },
      { snow: 0, high: 34, low: 18 }, { snow: 1, high: 32, low: 16 },
      { snow: 1, high: 29, low: 13 },
    ],
    season_total_in: 210, avalanche_danger: "Low",
    last_updated: "2026-02-26 07:00",
    lat: 38.802, lon: -120.080,
    webcam_url: "https://www.sierraattahoe.com/mountain-information/web-cams/",
    trail_map_url: "https://www.sierraattahoe.com/mountain-information/trail-map/",
    trail_map_pdf_url: "",
  },

  // ── Wasatch ─────────────────────────────────────────────
  {
    id: 25, name: "Alta", region: "wasatch", country: "USA", state: "UT",
    elevation: { base: 8530, summit: 10550 },
    base_in: 130, new48h_in: 10, forecast7d_in: 22,
    open_trails: 116, total_trails: 116, lifts_open: 11, lifts_total: 11,
    rating: 4.8, surface: "Powder", wind_mph: 12, temp_f: 18,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { snow: 5, high: 20, low: 4 }, { snow: 6, high: 18, low: 2 },
      { snow: 5, high: 19, low: 3 }, { snow: 3, high: 23, low: 7 },
      { snow: 1, high: 26, low: 10 }, { snow: 1, high: 25, low: 9 },
      { snow: 1, high: 22, low: 6 },
    ],
    season_total_in: 420, avalanche_danger: "Considerable",
    last_updated: "2026-02-26 06:00",
    lat: 40.588, lon: -111.637,
    webcam_url: "https://www.alta.com/conditions/webcams",
    trail_map_url: "https://www.alta.com/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 26, name: "Brighton", region: "wasatch", country: "USA", state: "UT",
    elevation: { base: 8755, summit: 10500 },
    base_in: 110, new48h_in: 8, forecast7d_in: 18,
    open_trails: 66, total_trails: 66, lifts_open: 7, lifts_total: 7,
    rating: 4.5, surface: "Powder", wind_mph: 10, temp_f: 20,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 21, intermediate: 40, advanced: 39 },
    forecast: [
      { snow: 4, high: 22, low: 6 }, { snow: 5, high: 20, low: 4 },
      { snow: 4, high: 21, low: 5 }, { snow: 2, high: 25, low: 9 },
      { snow: 1, high: 28, low: 12 }, { snow: 1, high: 27, low: 11 },
      { snow: 1, high: 24, low: 8 },
    ],
    season_total_in: 390, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 06:00",
    lat: 40.598, lon: -111.583,
    webcam_url: "https://brightonresort.com/conditions",
    trail_map_url: "https://brightonresort.com/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 27, name: "Deer Valley", region: "wasatch", country: "USA", state: "UT",
    elevation: { base: 6570, summit: 9570 },
    base_in: 85, new48h_in: 5, forecast7d_in: 12,
    open_trails: 103, total_trails: 103, lifts_open: 21, lifts_total: 21,
    rating: 4.8, surface: "Groomed", wind_mph: 8, temp_f: 22,
    visibility: "Excellent", groomed_today: true, status: "open",
    terrain: { beginner: 27, intermediate: 41, advanced: 32 },
    forecast: [
      { snow: 2, high: 24, low: 8 }, { snow: 3, high: 22, low: 6 },
      { snow: 3, high: 23, low: 7 }, { snow: 2, high: 27, low: 11 },
      { snow: 1, high: 30, low: 14 }, { snow: 0, high: 31, low: 15 },
      { snow: 1, high: 28, low: 12 },
    ],
    season_total_in: 250, avalanche_danger: "Low",
    last_updated: "2026-02-26 06:00",
    lat: 40.637, lon: -111.478,
    webcam_url: "https://www.deervalley.com/explore-the-mountain/mountain-report",
    trail_map_url: "https://www.deervalley.com/explore-the-mountain/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 28, name: "Solitude", region: "wasatch", country: "USA", state: "UT",
    elevation: { base: 7988, summit: 10035 },
    base_in: 100, new48h_in: 7, forecast7d_in: 16,
    open_trails: 82, total_trails: 82, lifts_open: 8, lifts_total: 8,
    rating: 4.6, surface: "Powder", wind_mph: 9, temp_f: 19,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 20, intermediate: 50, advanced: 30 },
    forecast: [
      { snow: 3, high: 21, low: 5 }, { snow: 4, high: 19, low: 3 },
      { snow: 4, high: 20, low: 4 }, { snow: 2, high: 24, low: 8 },
      { snow: 1, high: 27, low: 11 }, { snow: 1, high: 26, low: 10 },
      { snow: 1, high: 23, low: 7 },
    ],
    season_total_in: 370, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 06:00",
    lat: 40.620, lon: -111.592,
    webcam_url: "https://www.solitudemountain.com/mountain-conditions/webcams",
    trail_map_url: "https://www.solitudemountain.com/mountain-conditions/trail-map",
    trail_map_pdf_url: "",
  },

  // ── Rockies ─────────────────────────────────────────────
  {
    id: 29, name: "Steamboat", region: "rockies", country: "USA", state: "CO",
    elevation: { base: 6900, summit: 10568 },
    base_in: 80, new48h_in: 5, forecast7d_in: 12,
    open_trails: 169, total_trails: 169, lifts_open: 16, lifts_total: 18,
    rating: 4.7, surface: "Packed Powder", wind_mph: 10, temp_f: 20,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 14, intermediate: 42, advanced: 44 },
    forecast: [
      { snow: 3, high: 22, low: 8 }, { snow: 5, high: 20, low: 6 },
      { snow: 4, high: 21, low: 7 }, { snow: 2, high: 25, low: 11 },
      { snow: 1, high: 28, low: 14 }, { snow: 0, high: 31, low: 17 },
      { snow: 2, high: 27, low: 13 },
    ],
    season_total_in: 280, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 40.457, lon: -106.804,
    webcam_url: "https://www.steamboat.com/the-mountain/mountain-report/webcams",
    trail_map_url: "https://www.steamboat.com/the-mountain/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 30, name: "Copper Mountain", region: "rockies", country: "USA", state: "CO",
    elevation: { base: 9712, summit: 12313 },
    base_in: 72, new48h_in: 4, forecast7d_in: 10,
    open_trails: 150, total_trails: 150, lifts_open: 22, lifts_total: 24,
    rating: 4.5, surface: "Packed Powder", wind_mph: 12, temp_f: 18,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 21, intermediate: 25, advanced: 54 },
    forecast: [
      { snow: 2, high: 20, low: 4 }, { snow: 3, high: 18, low: 2 },
      { snow: 3, high: 19, low: 3 }, { snow: 1, high: 23, low: 7 },
      { snow: 0, high: 26, low: 10 }, { snow: 0, high: 28, low: 12 },
      { snow: 1, high: 24, low: 8 },
    ],
    season_total_in: 235, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 39.502, lon: -106.151,
    webcam_url: "https://www.coppercolorado.com/the-mountain/conditions-weather/webcams",
    trail_map_url: "https://www.coppercolorado.com/the-mountain/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 31, name: "Winter Park", region: "rockies", country: "USA", state: "CO",
    elevation: { base: 9000, summit: 12060 },
    base_in: 88, new48h_in: 6, forecast7d_in: 14,
    open_trails: 166, total_trails: 166, lifts_open: 24, lifts_total: 25,
    rating: 4.6, surface: "Packed Powder", wind_mph: 11, temp_f: 16,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 8, intermediate: 19, advanced: 73 },
    forecast: [
      { snow: 3, high: 18, low: 2 }, { snow: 4, high: 16, low: 0 },
      { snow: 3, high: 17, low: 1 }, { snow: 2, high: 21, low: 5 },
      { snow: 1, high: 24, low: 8 }, { snow: 0, high: 26, low: 10 },
      { snow: 1, high: 22, low: 6 },
    ],
    season_total_in: 300, avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 39.887, lon: -105.763,
    webcam_url: "https://www.winterparkresort.com/the-mountain/webcams",
    trail_map_url: "https://www.winterparkresort.com/the-mountain/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 32, name: "Crested Butte", region: "rockies", country: "USA", state: "CO",
    elevation: { base: 9375, summit: 12162 },
    base_in: 76, new48h_in: 5, forecast7d_in: 11,
    open_trails: 121, total_trails: 121, lifts_open: 15, lifts_total: 16,
    rating: 4.7, surface: "Packed Powder", wind_mph: 10, temp_f: 14,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 15, intermediate: 24, advanced: 61 },
    forecast: [
      { snow: 2, high: 16, low: 0 }, { snow: 4, high: 14, low: -2 },
      { snow: 3, high: 15, low: -1 }, { snow: 1, high: 19, low: 3 },
      { snow: 0, high: 22, low: 6 }, { snow: 1, high: 21, low: 5 },
      { snow: 0, high: 18, low: 2 },
    ],
    season_total_in: 245, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 38.899, lon: -106.965,
    webcam_url: "https://www.skicb.com/the-mountain/webcams",
    trail_map_url: "https://www.skicb.com/the-mountain/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 33, name: "Taos Ski Valley", region: "rockies", country: "USA", state: "NM",
    elevation: { base: 9207, summit: 12481 },
    base_in: 68, new48h_in: 3, forecast7d_in: 8,
    open_trails: 110, total_trails: 110, lifts_open: 14, lifts_total: 15,
    rating: 4.6, surface: "Packed Powder", wind_mph: 14, temp_f: 16,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 24, intermediate: 25, advanced: 51 },
    forecast: [
      { snow: 1, high: 18, low: 2 }, { snow: 2, high: 16, low: 0 },
      { snow: 2, high: 17, low: 1 }, { snow: 1, high: 21, low: 5 },
      { snow: 0, high: 24, low: 8 }, { snow: 1, high: 23, low: 7 },
      { snow: 1, high: 20, low: 4 },
    ],
    season_total_in: 210, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 36.596, lon: -105.454,
    webcam_url: "https://www.skitaos.com/conditions-cams",
    trail_map_url: "https://www.skitaos.com/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 34, name: "Big Sky", region: "rockies", country: "USA", state: "MT",
    elevation: { base: 7500, summit: 11166 },
    base_in: 90, new48h_in: 6, forecast7d_in: 14,
    open_trails: 317, total_trails: 317, lifts_open: 36, lifts_total: 39,
    rating: 4.7, surface: "Packed Powder", wind_mph: 12, temp_f: 12,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 15, intermediate: 25, advanced: 60 },
    forecast: [
      { snow: 3, high: 14, low: -2 }, { snow: 4, high: 12, low: -4 },
      { snow: 4, high: 13, low: -3 }, { snow: 2, high: 17, low: 1 },
      { snow: 1, high: 20, low: 4 }, { snow: 0, high: 22, low: 6 },
      { snow: 0, high: 18, low: 2 },
    ],
    season_total_in: 310, avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 45.284, lon: -111.401,
    webcam_url: "https://bigskyresort.com/conditions-webcams",
    trail_map_url: "https://bigskyresort.com/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 35, name: "Arapahoe Basin", region: "rockies", country: "USA", state: "CO",
    elevation: { base: 10780, summit: 13050 },
    base_in: 64, new48h_in: 3, forecast7d_in: 7,
    open_trails: 147, total_trails: 147, lifts_open: 9, lifts_total: 9,
    rating: 4.5, surface: "Packed Powder", wind_mph: 18, temp_f: 8,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 10, intermediate: 30, advanced: 60 },
    forecast: [
      { snow: 1, high: 10, low: -6 }, { snow: 2, high: 8, low: -8 },
      { snow: 2, high: 9, low: -7 }, { snow: 1, high: 13, low: -3 },
      { snow: 0, high: 16, low: 0 }, { snow: 0, high: 18, low: 2 },
      { snow: 1, high: 14, low: -2 },
    ],
    season_total_in: 220, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 39.642, lon: -105.872,
    webcam_url: "https://www.arapahoebasin.com/conditions-weather/webcams/",
    trail_map_url: "https://www.arapahoebasin.com/the-mountain/trail-map/",
    trail_map_pdf_url: "",
  },
  {
    id: 36, name: "Keystone", region: "rockies", country: "USA", state: "CO",
    elevation: { base: 9280, summit: 12408 },
    base_in: 70, new48h_in: 4, forecast7d_in: 9,
    open_trails: 128, total_trails: 128, lifts_open: 20, lifts_total: 20,
    rating: 4.5, surface: "Groomed", wind_mph: 10, temp_f: 16,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 12, intermediate: 37, advanced: 51 },
    forecast: [
      { snow: 2, high: 18, low: 2 }, { snow: 3, high: 16, low: 0 },
      { snow: 2, high: 17, low: 1 }, { snow: 1, high: 21, low: 5 },
      { snow: 0, high: 24, low: 8 }, { snow: 0, high: 26, low: 10 },
      { snow: 1, high: 22, low: 6 },
    ],
    season_total_in: 195, avalanche_danger: "Low",
    last_updated: "2026-02-26 07:00",
    lat: 39.606, lon: -105.970,
    webcam_url: "https://www.keystoneresort.com/the-mountain/webcams.aspx",
    trail_map_url: "https://www.keystoneresort.com/the-mountain/trail-map.aspx",
    trail_map_pdf_url: "",
  },

  // ── Cascades ────────────────────────────────────────────
  {
    id: 37, name: "Stevens Pass", region: "cascades", country: "USA", state: "WA",
    elevation: { base: 4061, summit: 5845 },
    base_in: 100, new48h_in: 8, forecast7d_in: 20,
    open_trails: 52, total_trails: 52, lifts_open: 10, lifts_total: 10,
    rating: 4.5, surface: "Powder", wind_mph: 16, temp_f: 26,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 11, intermediate: 54, advanced: 35 },
    forecast: [
      { snow: 5, high: 28, low: 18 }, { snow: 6, high: 26, low: 16 },
      { snow: 4, high: 27, low: 17 }, { snow: 2, high: 31, low: 21 },
      { snow: 1, high: 34, low: 24 }, { snow: 1, high: 33, low: 23 },
      { snow: 1, high: 30, low: 20 },
    ],
    season_total_in: 380, avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 47.745, lon: -121.089,
    webcam_url: "https://www.stevenspass.com/the-mountain/conditions-weather/webcams",
    trail_map_url: "https://www.stevenspass.com/the-mountain/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 38, name: "Crystal Mountain", region: "cascades", country: "USA", state: "WA",
    elevation: { base: 4400, summit: 7012 },
    base_in: 115, new48h_in: 9, forecast7d_in: 22,
    open_trails: 57, total_trails: 57, lifts_open: 10, lifts_total: 11,
    rating: 4.6, surface: "Powder", wind_mph: 14, temp_f: 24,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 13, intermediate: 57, advanced: 30 },
    forecast: [
      { snow: 5, high: 26, low: 16 }, { snow: 7, high: 24, low: 14 },
      { snow: 4, high: 25, low: 15 }, { snow: 3, high: 29, low: 19 },
      { snow: 1, high: 32, low: 22 }, { snow: 1, high: 31, low: 21 },
      { snow: 1, high: 28, low: 18 },
    ],
    season_total_in: 400, avalanche_danger: "Considerable",
    last_updated: "2026-02-26 07:00",
    lat: 46.935, lon: -121.501,
    webcam_url: "https://www.crystalmountainresort.com/the-mountain/webcams",
    trail_map_url: "https://www.crystalmountainresort.com/the-mountain/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 39, name: "Mt. Hood Meadows", region: "cascades", country: "USA", state: "OR",
    elevation: { base: 5380, summit: 7300 },
    base_in: 95, new48h_in: 7, forecast7d_in: 16,
    open_trails: 87, total_trails: 87, lifts_open: 11, lifts_total: 12,
    rating: 4.5, surface: "Packed Powder", wind_mph: 15, temp_f: 26,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 15, intermediate: 50, advanced: 35 },
    forecast: [
      { snow: 4, high: 28, low: 18 }, { snow: 5, high: 26, low: 16 },
      { snow: 3, high: 27, low: 17 }, { snow: 2, high: 31, low: 21 },
      { snow: 1, high: 34, low: 24 }, { snow: 0, high: 33, low: 23 },
      { snow: 1, high: 30, low: 20 },
    ],
    season_total_in: 350, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 07:00",
    lat: 45.331, lon: -121.665,
    webcam_url: "https://www.skihood.com/mountain-conditions/webcams",
    trail_map_url: "https://www.skihood.com/mountain-conditions/trail-map",
    trail_map_pdf_url: "",
  },

  // ── Northeast ───────────────────────────────────────────
  {
    id: 40, name: "Sugarbush", region: "northeast", country: "USA", state: "VT",
    elevation: { base: 1483, summit: 4083 },
    base_in: 42, new48h_in: 3, forecast7d_in: 8,
    open_trails: 111, total_trails: 111, lifts_open: 16, lifts_total: 16,
    rating: 4.5, surface: "Packed Powder", wind_mph: 12, temp_f: 14,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 20, intermediate: 45, advanced: 35 },
    forecast: [
      { snow: 1, high: 16, low: 0 }, { snow: 2, high: 14, low: -2 },
      { snow: 2, high: 15, low: -1 }, { snow: 1, high: 19, low: 3 },
      { snow: 0, high: 22, low: 6 }, { snow: 1, high: 21, low: 5 },
      { snow: 1, high: 18, low: 2 },
    ],
    season_total_in: 165, avalanche_danger: "Low",
    last_updated: "2026-02-26 06:00",
    lat: 44.137, lon: -72.906,
    webcam_url: "https://www.sugarbush.com/conditions-webcams",
    trail_map_url: "https://www.sugarbush.com/trail-maps",
    trail_map_pdf_url: "",
  },
  {
    id: 41, name: "Jay Peak", region: "northeast", country: "USA", state: "VT",
    elevation: { base: 1815, summit: 3968 },
    base_in: 55, new48h_in: 5, forecast7d_in: 12,
    open_trails: 81, total_trails: 81, lifts_open: 9, lifts_total: 9,
    rating: 4.6, surface: "Powder", wind_mph: 14, temp_f: 10,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 20, intermediate: 40, advanced: 40 },
    forecast: [
      { snow: 2, high: 12, low: -4 }, { snow: 3, high: 10, low: -6 },
      { snow: 3, high: 11, low: -5 }, { snow: 2, high: 15, low: -1 },
      { snow: 1, high: 18, low: 2 }, { snow: 0, high: 20, low: 4 },
      { snow: 1, high: 16, low: 0 },
    ],
    season_total_in: 220, avalanche_danger: "Low",
    last_updated: "2026-02-26 06:00",
    lat: 44.926, lon: -72.529,
    webcam_url: "https://www.jaypeakresort.com/conditions-cams",
    trail_map_url: "https://www.jaypeakresort.com/trail-maps",
    trail_map_pdf_url: "",
  },
  {
    id: 42, name: "Sunday River", region: "northeast", country: "USA", state: "ME",
    elevation: { base: 800, summit: 3140 },
    base_in: 38, new48h_in: 2, forecast7d_in: 6,
    open_trails: 135, total_trails: 135, lifts_open: 18, lifts_total: 18,
    rating: 4.4, surface: "Groomed", wind_mph: 16, temp_f: 12,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 25, intermediate: 35, advanced: 40 },
    forecast: [
      { snow: 1, high: 14, low: -2 }, { snow: 1, high: 12, low: -4 },
      { snow: 2, high: 13, low: -3 }, { snow: 1, high: 17, low: 1 },
      { snow: 0, high: 20, low: 4 }, { snow: 0, high: 22, low: 6 },
      { snow: 1, high: 18, low: 2 },
    ],
    season_total_in: 140, avalanche_danger: "Low",
    last_updated: "2026-02-26 06:00",
    lat: 44.473, lon: -70.857,
    webcam_url: "https://www.sundayriver.com/conditions-webcams",
    trail_map_url: "https://www.sundayriver.com/trail-maps",
    trail_map_pdf_url: "",
  },
  {
    id: 43, name: "Sugarloaf", region: "northeast", country: "USA", state: "ME",
    elevation: { base: 1417, summit: 4237 },
    base_in: 48, new48h_in: 4, forecast7d_in: 10,
    open_trails: 162, total_trails: 162, lifts_open: 13, lifts_total: 15,
    rating: 4.5, surface: "Packed Powder", wind_mph: 18, temp_f: 8,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 22, intermediate: 32, advanced: 46 },
    forecast: [
      { snow: 2, high: 10, low: -6 }, { snow: 3, high: 8, low: -8 },
      { snow: 2, high: 9, low: -7 }, { snow: 1, high: 13, low: -3 },
      { snow: 0, high: 16, low: 0 }, { snow: 1, high: 15, low: -1 },
      { snow: 1, high: 12, low: -4 },
    ],
    season_total_in: 180, avalanche_danger: "Low",
    last_updated: "2026-02-26 06:00",
    lat: 45.031, lon: -70.313,
    webcam_url: "https://www.sugarloaf.com/conditions-webcams",
    trail_map_url: "https://www.sugarloaf.com/trail-map",
    trail_map_pdf_url: "",
  },
  {
    id: 44, name: "Whiteface", region: "northeast", country: "USA", state: "NY",
    elevation: { base: 1220, summit: 4867 },
    base_in: 35, new48h_in: 2, forecast7d_in: 5,
    open_trails: 90, total_trails: 90, lifts_open: 10, lifts_total: 11,
    rating: 4.4, surface: "Groomed", wind_mph: 20, temp_f: 6,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 20, intermediate: 42, advanced: 38 },
    forecast: [
      { snow: 1, high: 8, low: -8 }, { snow: 1, high: 6, low: -10 },
      { snow: 1, high: 7, low: -9 }, { snow: 0, high: 11, low: -5 },
      { snow: 0, high: 14, low: -2 }, { snow: 1, high: 13, low: -3 },
      { snow: 1, high: 10, low: -6 },
    ],
    season_total_in: 130, avalanche_danger: "Low",
    last_updated: "2026-02-26 06:00",
    lat: 44.366, lon: -73.903,
    webcam_url: "https://www.whiteface.com/conditions-webcams",
    trail_map_url: "https://www.whiteface.com/trail-map",
    trail_map_pdf_url: "",
  },

  // ── Alps ────────────────────────────────────────────────
  {
    id: 45, name: "St. Anton", region: "alps", country: "Austria", state: "",
    elevation: { base: 4265, summit: 9222 },
    base_in: 75, new48h_in: 6, forecast7d_in: 14,
    open_trails: 305, total_trails: 305, lifts_open: 82, lifts_total: 88,
    rating: 4.8, surface: "Packed Powder", wind_mph: 10, temp_f: 18,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 30, intermediate: 40, advanced: 30 },
    forecast: [
      { snow: 3, high: 20, low: 4 }, { snow: 4, high: 18, low: 2 },
      { snow: 3, high: 19, low: 3 }, { snow: 2, high: 23, low: 7 },
      { snow: 1, high: 26, low: 10 }, { snow: 0, high: 27, low: 11 },
      { snow: 1, high: 24, low: 8 },
    ],
    season_total_in: 280, avalanche_danger: "Considerable",
    last_updated: "2026-02-26 08:00",
    lat: 47.130, lon: 10.268,
    webcam_url: "https://www.stantonamarlberg.com/en/winter/webcams",
    trail_map_url: "https://www.stantonamarlberg.com/en/winter/ski-area",
    trail_map_pdf_url: "",
  },
  {
    id: 46, name: "Lech Zürs", region: "alps", country: "Austria", state: "",
    elevation: { base: 4757, summit: 9186 },
    base_in: 80, new48h_in: 5, forecast7d_in: 12,
    open_trails: 305, total_trails: 305, lifts_open: 82, lifts_total: 88,
    rating: 4.7, surface: "Packed Powder", wind_mph: 8, temp_f: 20,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 30, intermediate: 40, advanced: 30 },
    forecast: [
      { snow: 2, high: 22, low: 6 }, { snow: 3, high: 20, low: 4 },
      { snow: 3, high: 21, low: 5 }, { snow: 1, high: 25, low: 9 },
      { snow: 0, high: 28, low: 12 }, { snow: 1, high: 27, low: 11 },
      { snow: 1, high: 24, low: 8 },
    ],
    season_total_in: 270, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 47.210, lon: 10.142,
    webcam_url: "https://www.lechzuers.com/en/winter/webcams",
    trail_map_url: "https://www.lechzuers.com/en/winter/ski-area",
    trail_map_pdf_url: "",
  },
  {
    id: 47, name: "Courchevel", region: "alps", country: "France", state: "",
    elevation: { base: 4101, summit: 9842 },
    base_in: 70, new48h_in: 4, forecast7d_in: 10,
    open_trails: 150, total_trails: 150, lifts_open: 58, lifts_total: 62,
    rating: 4.7, surface: "Groomed", wind_mph: 8, temp_f: 22,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 25, intermediate: 40, advanced: 35 },
    forecast: [
      { snow: 2, high: 24, low: 8 }, { snow: 3, high: 22, low: 6 },
      { snow: 2, high: 23, low: 7 }, { snow: 1, high: 27, low: 11 },
      { snow: 0, high: 30, low: 14 }, { snow: 1, high: 29, low: 13 },
      { snow: 1, high: 26, low: 10 },
    ],
    season_total_in: 240, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 45.415, lon: 6.634,
    webcam_url: "https://www.courchevel.com/webcams",
    trail_map_url: "https://www.courchevel.com/ski-area-map",
    trail_map_pdf_url: "",
  },
  {
    id: 48, name: "Méribel", region: "alps", country: "France", state: "",
    elevation: { base: 3609, summit: 9843 },
    base_in: 65, new48h_in: 4, forecast7d_in: 10,
    open_trails: 150, total_trails: 150, lifts_open: 42, lifts_total: 45,
    rating: 4.6, surface: "Groomed", wind_mph: 9, temp_f: 23,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 28, intermediate: 40, advanced: 32 },
    forecast: [
      { snow: 2, high: 25, low: 9 }, { snow: 3, high: 23, low: 7 },
      { snow: 2, high: 24, low: 8 }, { snow: 1, high: 28, low: 12 },
      { snow: 0, high: 31, low: 15 }, { snow: 1, high: 30, low: 14 },
      { snow: 1, high: 27, low: 11 },
    ],
    season_total_in: 230, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 45.397, lon: 6.566,
    webcam_url: "https://www.meribel.net/webcams.html",
    trail_map_url: "https://www.meribel.net/ski-area/ski-area-map.html",
    trail_map_pdf_url: "",
  },
  {
    id: 49, name: "St. Moritz", region: "alps", country: "Switzerland", state: "",
    elevation: { base: 5748, summit: 10030 },
    base_in: 60, new48h_in: 3, forecast7d_in: 8,
    open_trails: 88, total_trails: 88, lifts_open: 24, lifts_total: 24,
    rating: 4.7, surface: "Groomed", wind_mph: 8, temp_f: 16,
    visibility: "Excellent", groomed_today: true, status: "open",
    terrain: { beginner: 25, intermediate: 35, advanced: 40 },
    forecast: [
      { snow: 1, high: 18, low: 2 }, { snow: 2, high: 16, low: 0 },
      { snow: 2, high: 17, low: 1 }, { snow: 1, high: 21, low: 5 },
      { snow: 0, high: 24, low: 8 }, { snow: 0, high: 23, low: 7 },
      { snow: 1, high: 20, low: 4 },
    ],
    season_total_in: 195, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 08:00",
    lat: 46.497, lon: 9.838,
    webcam_url: "https://www.stmoritz.com/en/winter/webcams/",
    trail_map_url: "https://www.stmoritz.com/en/winter/skiing/ski-area/",
    trail_map_pdf_url: "",
  },
  {
    id: 50, name: "Kitzbühel", region: "alps", country: "Austria", state: "",
    elevation: { base: 2625, summit: 6562 },
    base_in: 50, new48h_in: 3, forecast7d_in: 8,
    open_trails: 170, total_trails: 170, lifts_open: 54, lifts_total: 57,
    rating: 4.7, surface: "Groomed", wind_mph: 7, temp_f: 24,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 30, intermediate: 42, advanced: 28 },
    forecast: [
      { snow: 1, high: 26, low: 10 }, { snow: 2, high: 24, low: 8 },
      { snow: 2, high: 25, low: 9 }, { snow: 1, high: 29, low: 13 },
      { snow: 0, high: 32, low: 16 }, { snow: 0, high: 31, low: 15 },
      { snow: 1, high: 28, low: 12 },
    ],
    season_total_in: 180, avalanche_danger: "Low",
    last_updated: "2026-02-26 08:00",
    lat: 47.449, lon: 12.392,
    webcam_url: "https://www.kitzbuehel.com/en/winter/webcams",
    trail_map_url: "https://www.kitzbuehel.com/en/winter/ski-area",
    trail_map_pdf_url: "",
  },

  // ── Japan ───────────────────────────────────────────────
  {
    id: 51, name: "Hakuba Valley", region: "japan", country: "Japan", state: "",
    elevation: { base: 2493, summit: 5906 },
    base_in: 140, new48h_in: 12, forecast7d_in: 28,
    open_trails: 137, total_trails: 137, lifts_open: 56, lifts_total: 56,
    rating: 4.7, surface: "Powder", wind_mph: 8, temp_f: 18,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 30, intermediate: 40, advanced: 30 },
    forecast: [
      { snow: 6, high: 20, low: 10 }, { snow: 8, high: 18, low: 8 },
      { snow: 5, high: 19, low: 9 }, { snow: 4, high: 23, low: 13 },
      { snow: 2, high: 26, low: 16 }, { snow: 2, high: 25, low: 15 },
      { snow: 1, high: 22, low: 12 },
    ],
    season_total_in: 460, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 09:00",
    lat: 36.698, lon: 137.832,
    webcam_url: "https://www.hakubavalley.com/en/",
    trail_map_url: "https://www.hakubavalley.com/en/",
    trail_map_pdf_url: "",
  },
  {
    id: 52, name: "Furano", region: "japan", country: "Japan", state: "",
    elevation: { base: 738, summit: 3458 },
    base_in: 155, new48h_in: 10, forecast7d_in: 24,
    open_trails: 28, total_trails: 28, lifts_open: 10, lifts_total: 10,
    rating: 4.6, surface: "Powder", wind_mph: 6, temp_f: 12,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 40, intermediate: 40, advanced: 20 },
    forecast: [
      { snow: 5, high: 14, low: 4 }, { snow: 6, high: 12, low: 2 },
      { snow: 5, high: 13, low: 3 }, { snow: 3, high: 17, low: 7 },
      { snow: 2, high: 20, low: 10 }, { snow: 2, high: 19, low: 9 },
      { snow: 1, high: 16, low: 6 },
    ],
    season_total_in: 490, avalanche_danger: "Low",
    last_updated: "2026-02-26 09:00",
    lat: 43.339, lon: 142.383,
    webcam_url: "https://www.princehotels.com/ski/furano/",
    trail_map_url: "https://www.princehotels.com/ski/furano/",
    trail_map_pdf_url: "",
  },
  {
    id: 53, name: "Myoko Kogen", region: "japan", country: "Japan", state: "",
    elevation: { base: 2297, summit: 4429 },
    base_in: 170, new48h_in: 14, forecast7d_in: 30,
    open_trails: 33, total_trails: 33, lifts_open: 15, lifts_total: 17,
    rating: 4.5, surface: "Powder", wind_mph: 10, temp_f: 16,
    visibility: "Fair", groomed_today: true, status: "open",
    terrain: { beginner: 30, intermediate: 40, advanced: 30 },
    forecast: [
      { snow: 7, high: 18, low: 8 }, { snow: 8, high: 16, low: 6 },
      { snow: 6, high: 17, low: 7 }, { snow: 4, high: 21, low: 11 },
      { snow: 2, high: 24, low: 14 }, { snow: 2, high: 23, low: 13 },
      { snow: 1, high: 20, low: 10 },
    ],
    season_total_in: 530, avalanche_danger: "Moderate",
    last_updated: "2026-02-26 09:00",
    lat: 36.867, lon: 138.683,
    webcam_url: "https://myokokogen.net/",
    trail_map_url: "https://myokokogen.net/",
    trail_map_pdf_url: "",
  },
  {
    id: 54, name: "Shiga Kogen", region: "japan", country: "Japan", state: "",
    elevation: { base: 4429, summit: 7218 },
    base_in: 120, new48h_in: 8, forecast7d_in: 18,
    open_trails: 83, total_trails: 83, lifts_open: 48, lifts_total: 51,
    rating: 4.5, surface: "Packed Powder", wind_mph: 8, temp_f: 14,
    visibility: "Good", groomed_today: true, status: "open",
    terrain: { beginner: 35, intermediate: 45, advanced: 20 },
    forecast: [
      { snow: 4, high: 16, low: 6 }, { snow: 5, high: 14, low: 4 },
      { snow: 4, high: 15, low: 5 }, { snow: 2, high: 19, low: 9 },
      { snow: 1, high: 22, low: 12 }, { snow: 1, high: 21, low: 11 },
      { snow: 1, high: 18, low: 8 },
    ],
    season_total_in: 380, avalanche_danger: "Low",
    last_updated: "2026-02-26 09:00",
    lat: 36.771, lon: 138.527,
    webcam_url: "https://www.shigakogen-ski.com/",
    trail_map_url: "https://www.shigakogen-ski.com/",
    trail_map_pdf_url: "",
  },
];

// Season snowfall comparison data
const SEASON_DATA = {
  labels: ["Niseko", "Mt. Baker", "Whistler", "Mammoth", "Snowbird", "Palisades"],
  current: [610, 520, 450, 382, 340, 310],
  avg: [520, 480, 400, 350, 300, 280],
};

// Weekly temperature outlook (°F)
const TEMP_OUTLOOK = {
  labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  high: [22, 26, 24, 20, 18, 16, 20],
  low:  [8,  12, 10,  4,  2,  0,  4],
};
